# Generated by Django 3.2.8 on 2021-12-08 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default='ank@gmanil.com', max_length=254),
        ),
    ]
