# Generated by Django 3.2.8 on 2021-11-20 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenities',
            name='name_for_property',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='features',
            name='name_for_property',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
