# Generated by Django 3.2.8 on 2021-11-20 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ets', '0002_auto_20211120_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenities',
            name='property_amenities',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ets.property'),
        ),
    ]
