# Generated by Django 3.2.8 on 2021-11-20 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ets', '0003_alter_amenities_property_amenities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
