# Generated by Django 3.2.8 on 2021-11-20 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ets', '0005_alter_property_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_complex', models.CharField(default='', max_length=1000)),
                ('flats', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ets.property')),
            ],
        ),
    ]
