# Generated by Django 3.2.8 on 2021-11-20 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ets', '0007_remove_complex_flats'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complex_Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('builder_name', models.CharField(max_length=1000)),
                ('complex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ets.complex')),
            ],
        ),
        migrations.CreateModel(
            name='Complex_Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_for_property', models.CharField(default='', max_length=1000)),
                ('materials_used', models.CharField(max_length=1000)),
                ('floor_plan', models.ImageField(upload_to='')),
                ('flat_size', models.CharField(max_length=1000)),
                ('flat_location', models.CharField(max_length=1000)),
                ('property_features', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ets.property')),
            ],
        ),
        migrations.CreateModel(
            name='Complex_Amenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_for_property', models.CharField(default='', max_length=1000)),
                ('name_amenities', models.CharField(max_length=1000)),
                ('property_amenities', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ets.property')),
            ],
        ),
    ]
