# Generated by Django 3.2.8 on 2021-11-20 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ets', '0008_complex_amenities_complex_features_complex_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complex_amenities',
            name='property_amenities',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ets.complex_property'),
        ),
        migrations.AlterField(
            model_name='complex_features',
            name='property_features',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ets.complex_property'),
        ),
    ]
