# Generated by Django 3.2.8 on 2021-11-22 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ets', '0010_property_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='picture',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
    ]
