# Generated by Django 3.2.8 on 2021-11-22 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ets', '0011_alter_property_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='picture',
        ),
    ]
