# Generated by Django 3.2.8 on 2021-11-25 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ets', '0015_alter_property_locations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='complex_amenities',
            name='property_amenities',
        ),
        migrations.RemoveField(
            model_name='complex_features',
            name='property_features',
        ),
        migrations.RemoveField(
            model_name='complex_property',
            name='complex',
        ),
        migrations.RemoveField(
            model_name='features',
            name='property_features',
        ),
        migrations.RemoveField(
            model_name='property',
            name='picture',
        ),
        migrations.AddField(
            model_name='property',
            name='amenities',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='property',
            name='flat_size',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='property',
            name='floor_plan',
            field=models.ImageField(default=False, upload_to=''),
        ),
        migrations.AddField(
            model_name='property',
            name='materials_used',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='property',
            name='builder_name',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='property',
            name='name',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.DeleteModel(
            name='Amenities',
        ),
        migrations.DeleteModel(
            name='Complex',
        ),
        migrations.DeleteModel(
            name='Complex_Amenities',
        ),
        migrations.DeleteModel(
            name='Complex_Features',
        ),
        migrations.DeleteModel(
            name='Complex_Property',
        ),
        migrations.DeleteModel(
            name='Features',
        ),
        migrations.AddField(
            model_name='pictures',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ets.property'),
        ),
    ]
