# Generated by Django 3.2.8 on 2021-11-25 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ets', '0016_auto_20211125_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
