# Generated by Django 3.2.8 on 2021-11-25 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ets', '0018_alter_property_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='pic',
            field=models.ImageField(default=False, upload_to=''),
        ),
    ]
