# Generated by Django 3.2.8 on 2021-12-01 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ets', '0022_property_flat_sqft'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='Puja_room',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='property',
            name='balconies',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='property',
            name='bathroom',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='property',
            name='bedroom',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
