# Generated by Django 3.2.8 on 2021-12-01 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ets', '0023_auto_20211201_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='booking_amount',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
