# Generated by Django 3.2.8 on 2021-12-01 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ets', '0024_property_booking_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='full_address',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
