# Generated by Django 3.2.8 on 2021-12-01 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ets', '0025_property_full_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='landmark',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
