# Generated by Django 3.2.8 on 2021-12-01 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ets', '0027_property_overlook'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='flooring',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
