# Generated by Django 3.2.8 on 2021-12-01 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ets', '0028_property_flooring'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='electricity',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
