# Generated by Django 3.2.8 on 2021-12-01 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ets', '0029_property_electricity'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='age',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
