# Generated by Django 3.2.8 on 2021-12-01 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ets', '0030_property_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='car_parking',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='property',
            name='water',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
