# Generated by Django 3.2.8 on 2021-12-09 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ets', '0031_auto_20211201_1952'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('email', models.CharField(max_length=1000)),
                ('address', models.CharField(max_length=1000)),
                ('phone', models.CharField(max_length=1000)),
                ('altphone', models.CharField(max_length=1000)),
            ],
        ),
    ]
